### ISSUE TITLE
Stop current Timer when starting a new one

### ISSUE THREAD

**Issue by luxflux** [twhiston/hk#1]
At the moment, my use case for the API is that I want to switch between different projects.
[The CLI I'm currently using](https://github.com/luxflux/dotfiles/blob/master/bin/hakuna-timer) supports stopping the current timer when starting a new one. It would be nice to see such a support here as well 😄

**Comment by twhiston** [comment]
As this is not exactly how the api works if you call start repeatedly would you instead be ok with me adding a custom command `timer new` instead where the action you want is composed? then the core commands can still match the api behaviour.

**Comment by luxflux** [comment]
Sure, or maybe a flag like `--stop-if-needed` (or whatever)?

**Comment by twhiston** [comment]
flag is actually more difficult as its a special case that would mean altering the command generator and adding stuff just for that, i'd rather do something separate and hand rolled (like the today command) if its all the same to you.

**Comment by twhiston** [comment]
started working on this in the 1.0.0-rc2 branch, `hk timer new` will stop and start a timer, but currently has no options or args

**Comment by twhiston** [comment]
added in 1.0.0-rc2
