### ISSUE TITLE
Projects not supported everywhere

### ISSUE THREAD

**Issue by luxflux** [twhiston/hk#2]
It looks like the client is currently lacking support for projects:
* `hk-darwin-amd64 projects` doesn't list any, even though I should see ~3 of them
* It's not possible to specify a project when starting a timer

**Comment by twhiston** [comment]
thanks very much for the report, will look into this ASAP

**Comment by luxflux** [comment]
Great, thanks!

**Comment by twhiston** [comment]
`hk projects` should be fixed in the rc2 branch (though you will need to build it yourself at the moment)

Passing a project flag (as well as the other options) to `hk timer start` should now also be fixed

**Comment by twhiston** [comment]
fixed in 1.0.0-rc2
